#!/usr/bin/env perl
# vim:ft=perl:sts=4:sw=4:et

use v5.36;

use aliased 'Geo::Proj::CCT';
use Math::Trig qw(deg2rad rad2deg);
use POSIX qw(floor);

my $cs = "+proj=longlat +ellps=GRS80";
#my $cs = "epsg:7844";
my $p = CCT->create($cs);

my $a = [deg2rad(144+(25+29.5244/60)/60), -deg2rad(37+(57+3.7203/60)/60)];
my $b = [deg2rad(143+(55+35.3839/60)/60), -deg2rad(37+(39+10.1561/60)/60)];

say "@$a";
say "@$b";

my ($d, $f, $r) = @{$p->geod($a, $b)};

say $d;
say fmod($f, 360);
say fmod($r+180, 360);

sub fmod {
    my ($x, $y) = @_;
    my $n = floor($x/$y);
    return $x - $n*$y;
}
