#!/usr/bin/env perl

use v5.36;
use aliased 'Geo::Proj::CCT';
my $p = CCT->crs2crs( 'epsg:7856', 'epsg:7844' )->norm;

use lib '.';
require "project.pm";
my $file    = "sample.csv";
my $kml     = "sample2.kml";
my $project = Project->new( name => $kml );

open my $fd, '<', $file;
while (<$fd>) {
    chomp;
    my ( $x, $y, $z, $d ) = split /,/;
    my $style = 'house';
    $style = 'ground' if $d =~ /G/;
    my ( $lon, $lat ) = @{ $p->fwd( [ $x, $y ] ) };
    my $desc  = sprintf "RL %.1f", $z;
    my $point = Point->new(
        id    => $d,
        x     => $lon,
        y     => $lat,
        z     => $z,
        style => $style,
        desc  => $desc
    );
    $project->point_add($point);
}
close $fd;

my $href = 'http://maps.google.com/mapfiles/kml/pal4/icon46.png';
$project->style_add(
    Style->new( id => 'house', color => 'ff00ff00', href => $href ) );
$project->style_add(
    Style->new( id => 'ground', color => 'ff7f00ff', href => $href ) );

#open $fd, '>', $kml;
#print $fd $project->kmlout;
#close $fd;

#say $project->kmlout;
say $project->tokml;
